
title: My Blog
description: This is my blog.
theme: bw-sandstone
# if homePage is not "posts", it should be the slug of a page
homePage: home
pageSize: 5
menu:
  - title: Home
    link: /
  - title: About
    link: /pages/about/
  - title: Blog
    link: /posts/page/1/
  - title: Social Networks
    isDropdown: true
    menu:
      - title: Facebook
        link: https://facebook.com
      - title: Twitter
        link: https://twitter.com
      - title: GitHub
        link: https://github.com

# options for bw-sandstone
aboutBlurb:
  title: About Me
  text: I am the author of this website and I do several cute things in my free time.
carousel:
  - imageUrl: /assets/images/Freezed_XRD.jpg
    link: https://wikipedia.com
    title: Wikipedia
    subtitle: The encyclopedia that anyone can edit.
  - imageUrl: /assets/images/Munich_Subway_Station.jpg
    title: Awesome Features
    subtitle: There are awesome features all over the place.
facebookPage: facebook
